// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEdition = `-- name: CreateEdition :one
INSERT INTO editions (game_id, year, name, status, started_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, game_id, year, name, status, started_at, ended_at, created_at
`

type CreateEditionParams struct {
	GameID    pgtype.UUID        `json:"game_id"`
	Year      int32              `json:"year"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateEdition(ctx context.Context, arg CreateEditionParams) (Edition, error) {
	row := q.db.QueryRow(ctx, createEdition,
		arg.GameID,
		arg.Year,
		arg.Name,
		arg.Status,
		arg.StartedAt,
	)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Year,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveEdition = `-- name: GetActiveEdition :one
SELECT e.id, e.game_id, e.year, e.name, e.status, e.started_at, e.ended_at, e.created_at FROM editions e
JOIN games g ON g.id = e.game_id
WHERE g.slug = $1 AND e.status = 'ongoing'
ORDER BY e.year DESC
LIMIT 1
`

func (q *Queries) GetActiveEdition(ctx context.Context, slug string) (Edition, error) {
	row := q.db.QueryRow(ctx, getActiveEdition, slug)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Year,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEditionByID = `-- name: GetEditionByID :one
SELECT id, game_id, year, name, status, started_at, ended_at, created_at FROM editions WHERE id = $1
`

func (q *Queries) GetEditionByID(ctx context.Context, id pgtype.UUID) (Edition, error) {
	row := q.db.QueryRow(ctx, getEditionByID, id)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Year,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEditionsByGame = `-- name: ListEditionsByGame :many
SELECT id, game_id, year, name, status, started_at, ended_at, created_at FROM editions WHERE game_id = $1 ORDER BY year DESC
`

func (q *Queries) ListEditionsByGame(ctx context.Context, gameID pgtype.UUID) ([]Edition, error) {
	rows, err := q.db.Query(ctx, listEditionsByGame, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Edition
	for rows.Next() {
		var i Edition
		if err := rows.Scan(
			&i.ID,
			&i.GameID,
			&i.Year,
			&i.Name,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEditionStatus = `-- name: UpdateEditionStatus :one
UPDATE editions SET status = $2, ended_at = $3 WHERE id = $1 RETURNING id, game_id, year, name, status, started_at, ended_at, created_at
`

type UpdateEditionStatusParams struct {
	ID      pgtype.UUID        `json:"id"`
	Status  string             `json:"status"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) UpdateEditionStatus(ctx context.Context, arg UpdateEditionStatusParams) (Edition, error) {
	row := q.db.QueryRow(ctx, updateEditionStatus, arg.ID, arg.Status, arg.EndedAt)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Year,
		&i.Name,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}
