// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (slug, name, cover_url, active)
VALUES ($1, $2, $3, $4)
RETURNING id, slug, name, cover_url, active, created_at
`

type CreateGameParams struct {
	Slug     string         `json:"slug"`
	Name     string         `json:"name"`
	CoverUrl sql.NullString `json:"cover_url"`
	Active   bool           `json:"active"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.Slug,
		arg.Name,
		arg.CoverUrl,
		arg.Active,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CoverUrl,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getGameBySlug = `-- name: GetGameBySlug :one
SELECT id, slug, name, cover_url, active, created_at FROM games WHERE slug = $1
`

func (q *Queries) GetGameBySlug(ctx context.Context, slug string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameBySlug, slug)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CoverUrl,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listGames = `-- name: ListGames :many
SELECT id, slug, name, cover_url, active, created_at FROM games ORDER BY name
`

func (q *Queries) ListGames(ctx context.Context) ([]Game, error) {
	rows, err := q.db.QueryContext(ctx, listGames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CoverUrl,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGame = `-- name: UpdateGame :one
UPDATE games
SET name = $2, cover_url = $3, active = $4
WHERE id = $1
RETURNING id, slug, name, cover_url, active, created_at
`

type UpdateGameParams struct {
	ID       uuid.UUID      `json:"id"`
	Name     string         `json:"name"`
	CoverUrl sql.NullString `json:"cover_url"`
	Active   bool           `json:"active"`
}

func (q *Queries) UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, updateGame,
		arg.ID,
		arg.Name,
		arg.CoverUrl,
		arg.Active,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CoverUrl,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
