// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (edition_id, team_a_id, team_b_id, round, scheduled_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, edition_id, team_a_id, team_b_id, round, scheduled_at, status, created_at
`

type CreateMatchParams struct {
	EditionID   uuid.UUID          `json:"edition_id"`
	TeamAID     uuid.UUID          `json:"team_a_id"`
	TeamBID     uuid.UUID          `json:"team_b_id"`
	Round       string             `json:"round"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.EditionID,
		arg.TeamAID,
		arg.TeamBID,
		arg.Round,
		arg.ScheduledAt,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.TeamAID,
		&i.TeamBID,
		&i.Round,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT m.id, m.edition_id, m.team_a_id, m.team_b_id, m.round, m.scheduled_at, m.status, m.created_at, mr.winner_id, mr.map, mr.score_a, mr.score_b, mr.played_at
FROM matches m
LEFT JOIN match_results mr ON mr.match_id = m.id
WHERE m.id = $1
`

type GetMatchByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	EditionID   uuid.UUID          `json:"edition_id"`
	TeamAID     uuid.UUID          `json:"team_a_id"`
	TeamBID     uuid.UUID          `json:"team_b_id"`
	Round       string             `json:"round"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	WinnerID    *uuid.UUID         `json:"winner_id"`
	Map         *string            `json:"map"`
	ScoreA      *int32             `json:"score_a"`
	ScoreB      *int32             `json:"score_b"`
	PlayedAt    pgtype.Timestamptz `json:"played_at"`
}

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (GetMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i GetMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.TeamAID,
		&i.TeamBID,
		&i.Round,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
		&i.WinnerID,
		&i.Map,
		&i.ScoreA,
		&i.ScoreB,
		&i.PlayedAt,
	)
	return i, err
}

const listMatchesByEdition = `-- name: ListMatchesByEdition :many
SELECT m.id, m.edition_id, m.team_a_id, m.team_b_id, m.round, m.scheduled_at, m.status, m.created_at, mr.winner_id, mr.map, mr.score_a, mr.score_b, mr.played_at
FROM matches m
LEFT JOIN match_results mr ON mr.match_id = m.id
WHERE m.edition_id = $1
ORDER BY COALESCE(mr.played_at, m.scheduled_at) DESC
`

type ListMatchesByEditionRow struct {
	ID          uuid.UUID          `json:"id"`
	EditionID   uuid.UUID          `json:"edition_id"`
	TeamAID     uuid.UUID          `json:"team_a_id"`
	TeamBID     uuid.UUID          `json:"team_b_id"`
	Round       string             `json:"round"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	WinnerID    *uuid.UUID         `json:"winner_id"`
	Map         *string            `json:"map"`
	ScoreA      *int32             `json:"score_a"`
	ScoreB      *int32             `json:"score_b"`
	PlayedAt    pgtype.Timestamptz `json:"played_at"`
}

func (q *Queries) ListMatchesByEdition(ctx context.Context, editionID uuid.UUID) ([]ListMatchesByEditionRow, error) {
	rows, err := q.db.Query(ctx, listMatchesByEdition, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesByEditionRow
	for rows.Next() {
		var i ListMatchesByEditionRow
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.TeamAID,
			&i.TeamBID,
			&i.Round,
			&i.ScheduledAt,
			&i.Status,
			&i.CreatedAt,
			&i.WinnerID,
			&i.Map,
			&i.ScoreA,
			&i.ScoreB,
			&i.PlayedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMatchResult = `-- name: RecordMatchResult :one
INSERT INTO match_results (match_id, winner_id, map, score_a, score_b, played_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, match_id, winner_id, map, score_a, score_b, played_at
`

type RecordMatchResultParams struct {
	MatchID  uuid.UUID          `json:"match_id"`
	WinnerID uuid.UUID          `json:"winner_id"`
	Map      *string            `json:"map"`
	ScoreA   int32              `json:"score_a"`
	ScoreB   int32              `json:"score_b"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

func (q *Queries) RecordMatchResult(ctx context.Context, arg RecordMatchResultParams) (MatchResult, error) {
	row := q.db.QueryRow(ctx, recordMatchResult,
		arg.MatchID,
		arg.WinnerID,
		arg.Map,
		arg.ScoreA,
		arg.ScoreB,
		arg.PlayedAt,
	)
	var i MatchResult
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.WinnerID,
		&i.Map,
		&i.ScoreA,
		&i.ScoreB,
		&i.PlayedAt,
	)
	return i, err
}

const updateMatchStatus = `-- name: UpdateMatchStatus :one
UPDATE matches SET status = $2 WHERE id = $1 RETURNING id, edition_id, team_a_id, team_b_id, round, scheduled_at, status, created_at
`

type UpdateMatchStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMatchStatus(ctx context.Context, arg UpdateMatchStatusParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatchStatus, arg.ID, arg.Status)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.TeamAID,
		&i.TeamBID,
		&i.Round,
		&i.ScheduledAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
