// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHighlight = `-- name: CreateHighlight :one
INSERT INTO highlights (edition_id, match_id, cf_stream_id, title, thumbnail_url, published_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, edition_id, match_id, cf_stream_id, title, thumbnail_url, published_at
`

type CreateHighlightParams struct {
	EditionID    uuid.UUID          `json:"edition_id"`
	MatchID      *uuid.UUID         `json:"match_id"`
	CfStreamID   string             `json:"cf_stream_id"`
	Title        string             `json:"title"`
	ThumbnailUrl *string            `json:"thumbnail_url"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) CreateHighlight(ctx context.Context, arg CreateHighlightParams) (Highlight, error) {
	row := q.db.QueryRow(ctx, createHighlight,
		arg.EditionID,
		arg.MatchID,
		arg.CfStreamID,
		arg.Title,
		arg.ThumbnailUrl,
		arg.PublishedAt,
	)
	var i Highlight
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.MatchID,
		&i.CfStreamID,
		&i.Title,
		&i.ThumbnailUrl,
		&i.PublishedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (edition_id, match_id, r2_key, url, caption, type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, edition_id, match_id, r2_key, url, caption, type, created_at
`

type CreateMediaParams struct {
	EditionID uuid.UUID  `json:"edition_id"`
	MatchID   *uuid.UUID `json:"match_id"`
	R2Key     string     `json:"r2_key"`
	Url       string     `json:"url"`
	Caption   *string    `json:"caption"`
	Type      string     `json:"type"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.EditionID,
		arg.MatchID,
		arg.R2Key,
		arg.Url,
		arg.Caption,
		arg.Type,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.MatchID,
		&i.R2Key,
		&i.Url,
		&i.Caption,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listHighlightsByEdition = `-- name: ListHighlightsByEdition :many
SELECT id, edition_id, match_id, cf_stream_id, title, thumbnail_url, published_at FROM highlights
WHERE edition_id = $1
ORDER BY published_at DESC
`

func (q *Queries) ListHighlightsByEdition(ctx context.Context, editionID uuid.UUID) ([]Highlight, error) {
	rows, err := q.db.Query(ctx, listHighlightsByEdition, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Highlight
	for rows.Next() {
		var i Highlight
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.MatchID,
			&i.CfStreamID,
			&i.Title,
			&i.ThumbnailUrl,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByEdition = `-- name: ListMediaByEdition :many
SELECT id, edition_id, match_id, r2_key, url, caption, type, created_at FROM media
WHERE edition_id = $1 AND type = $2
ORDER BY created_at DESC
`

type ListMediaByEditionParams struct {
	EditionID uuid.UUID `json:"edition_id"`
	Type      string    `json:"type"`
}

func (q *Queries) ListMediaByEdition(ctx context.Context, arg ListMediaByEditionParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByEdition, arg.EditionID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.EditionID,
			&i.MatchID,
			&i.R2Key,
			&i.Url,
			&i.Caption,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
