// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Edition struct {
	ID        pgtype.UUID        `json:"id"`
	GameID    pgtype.UUID        `json:"game_id"`
	Year      int32              `json:"year"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	EndedAt   pgtype.Timestamptz `json:"ended_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EditionTeam struct {
	ID             pgtype.UUID        `json:"id"`
	EditionID      pgtype.UUID        `json:"edition_id"`
	TeamID         pgtype.UUID        `json:"team_id"`
	Seed           *int32             `json:"seed"`
	FinalPlacement *int32             `json:"final_placement"`
	Wins           int32              `json:"wins"`
	Losses         int32              `json:"losses"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CoverUrl  *string            `json:"cover_url"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Highlight struct {
	ID           pgtype.UUID        `json:"id"`
	EditionID    pgtype.UUID        `json:"edition_id"`
	MatchID      pgtype.UUID        `json:"match_id"`
	CfStreamID   string             `json:"cf_stream_id"`
	Title        string             `json:"title"`
	ThumbnailUrl *string            `json:"thumbnail_url"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
}

type Match struct {
	ID          pgtype.UUID        `json:"id"`
	EditionID   pgtype.UUID        `json:"edition_id"`
	TeamAID     pgtype.UUID        `json:"team_a_id"`
	TeamBID     pgtype.UUID        `json:"team_b_id"`
	Round       string             `json:"round"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MatchResult struct {
	ID       pgtype.UUID        `json:"id"`
	MatchID  pgtype.UUID        `json:"match_id"`
	WinnerID pgtype.UUID        `json:"winner_id"`
	Map      *string            `json:"map"`
	ScoreA   int32              `json:"score_a"`
	ScoreB   int32              `json:"score_b"`
	PlayedAt pgtype.Timestamptz `json:"played_at"`
}

type Medium struct {
	ID        pgtype.UUID        `json:"id"`
	EditionID pgtype.UUID        `json:"edition_id"`
	MatchID   pgtype.UUID        `json:"match_id"`
	R2Key     string             `json:"r2_key"`
	Url       string             `json:"url"`
	Caption   *string            `json:"caption"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Player struct {
	ID        pgtype.UUID        `json:"id"`
	SgaUserID *int32             `json:"sga_user_id"`
	Ign       string             `json:"ign"`
	AvatarUrl *string            `json:"avatar_url"`
	Role      *string            `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Roster struct {
	ID            pgtype.UUID        `json:"id"`
	EditionTeamID pgtype.UUID        `json:"edition_team_id"`
	PlayerID      pgtype.UUID        `json:"player_id"`
	IsCaptain     bool               `json:"is_captain"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	LogoUrl      *string            `json:"logo_url"`
	PrimaryColor *string            `json:"primary_color"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
