// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayerToRoster = `-- name: AddPlayerToRoster :one
INSERT INTO rosters (edition_team_id, player_id, is_captain)
VALUES ($1, $2, $3)
RETURNING id, edition_team_id, player_id, is_captain, created_at
`

type AddPlayerToRosterParams struct {
	EditionTeamID uuid.UUID `json:"edition_team_id"`
	PlayerID      uuid.UUID `json:"player_id"`
	IsCaptain     bool      `json:"is_captain"`
}

func (q *Queries) AddPlayerToRoster(ctx context.Context, arg AddPlayerToRosterParams) (Roster, error) {
	row := q.db.QueryRow(ctx, addPlayerToRoster, arg.EditionTeamID, arg.PlayerID, arg.IsCaptain)
	var i Roster
	err := row.Scan(
		&i.ID,
		&i.EditionTeamID,
		&i.PlayerID,
		&i.IsCaptain,
		&i.CreatedAt,
	)
	return i, err
}

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (sga_user_id, ign, avatar_url, role)
VALUES ($1, $2, $3, $4)
RETURNING id, sga_user_id, ign, avatar_url, role, created_at
`

type CreatePlayerParams struct {
	SgaUserID *int32  `json:"sga_user_id"`
	Ign       string  `json:"ign"`
	AvatarUrl *string `json:"avatar_url"`
	Role      *string `json:"role"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.SgaUserID,
		arg.Ign,
		arg.AvatarUrl,
		arg.Role,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.SgaUserID,
		&i.Ign,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, sga_user_id, ign, avatar_url, role, created_at FROM players WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.SgaUserID,
		&i.Ign,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listPlayersByEditionTeam = `-- name: ListPlayersByEditionTeam :many
SELECT p.id, p.sga_user_id, p.ign, p.avatar_url, p.role, p.created_at, r.is_captain, r.edition_team_id
FROM players p
JOIN rosters r ON r.player_id = p.id
WHERE r.edition_team_id = $1
ORDER BY r.is_captain DESC, p.ign
`

type ListPlayersByEditionTeamRow struct {
	ID            uuid.UUID          `json:"id"`
	SgaUserID     *int32             `json:"sga_user_id"`
	Ign           string             `json:"ign"`
	AvatarUrl     *string            `json:"avatar_url"`
	Role          *string            `json:"role"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	IsCaptain     bool               `json:"is_captain"`
	EditionTeamID uuid.UUID          `json:"edition_team_id"`
}

func (q *Queries) ListPlayersByEditionTeam(ctx context.Context, editionTeamID uuid.UUID) ([]ListPlayersByEditionTeamRow, error) {
	rows, err := q.db.Query(ctx, listPlayersByEditionTeam, editionTeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayersByEditionTeamRow
	for rows.Next() {
		var i ListPlayersByEditionTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.SgaUserID,
			&i.Ign,
			&i.AvatarUrl,
			&i.Role,
			&i.CreatedAt,
			&i.IsCaptain,
			&i.EditionTeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players SET ign = $2, avatar_url = $3, role = $4 WHERE id = $1 RETURNING id, sga_user_id, ign, avatar_url, role, created_at
`

type UpdatePlayerParams struct {
	ID        uuid.UUID `json:"id"`
	Ign       string    `json:"ign"`
	AvatarUrl *string   `json:"avatar_url"`
	Role      *string   `json:"role"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer,
		arg.ID,
		arg.Ign,
		arg.AvatarUrl,
		arg.Role,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.SgaUserID,
		&i.Ign,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
