// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamToEdition = `-- name: AddTeamToEdition :one
INSERT INTO edition_teams (edition_id, team_id, seed)
VALUES ($1, $2, $3)
RETURNING id, edition_id, team_id, seed, final_placement, wins, losses, created_at
`

type AddTeamToEditionParams struct {
	EditionID pgtype.UUID `json:"edition_id"`
	TeamID    pgtype.UUID `json:"team_id"`
	Seed      *int32      `json:"seed"`
}

func (q *Queries) AddTeamToEdition(ctx context.Context, arg AddTeamToEditionParams) (EditionTeam, error) {
	row := q.db.QueryRow(ctx, addTeamToEdition, arg.EditionID, arg.TeamID, arg.Seed)
	var i EditionTeam
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.TeamID,
		&i.Seed,
		&i.FinalPlacement,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, slug, logo_url, primary_color)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, logo_url, primary_color, created_at
`

type CreateTeamParams struct {
	Name         string  `json:"name"`
	Slug         string  `json:"slug"`
	LogoUrl      *string `json:"logo_url"`
	PrimaryColor *string `json:"primary_color"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Slug,
		arg.LogoUrl,
		arg.PrimaryColor,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.CreatedAt,
	)
	return i, err
}

const getEditionTeamByID = `-- name: GetEditionTeamByID :one
SELECT id, edition_id, team_id, seed, final_placement, wins, losses, created_at FROM edition_teams WHERE id = $1
`

func (q *Queries) GetEditionTeamByID(ctx context.Context, id pgtype.UUID) (EditionTeam, error) {
	row := q.db.QueryRow(ctx, getEditionTeamByID, id)
	var i EditionTeam
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.TeamID,
		&i.Seed,
		&i.FinalPlacement,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, name, slug, logo_url, primary_color, created_at FROM teams WHERE slug = $1
`

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.CreatedAt,
	)
	return i, err
}

const listTeamsByEdition = `-- name: ListTeamsByEdition :many
SELECT t.id, t.name, t.slug, t.logo_url, t.primary_color, t.created_at, et.id AS edition_team_id, et.seed, et.final_placement, et.wins, et.losses
FROM teams t
JOIN edition_teams et ON et.team_id = t.id
WHERE et.edition_id = $1
ORDER BY et.wins DESC, et.losses ASC
`

type ListTeamsByEditionRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	LogoUrl        *string            `json:"logo_url"`
	PrimaryColor   *string            `json:"primary_color"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	EditionTeamID  pgtype.UUID        `json:"edition_team_id"`
	Seed           *int32             `json:"seed"`
	FinalPlacement *int32             `json:"final_placement"`
	Wins           int32              `json:"wins"`
	Losses         int32              `json:"losses"`
}

func (q *Queries) ListTeamsByEdition(ctx context.Context, editionID pgtype.UUID) ([]ListTeamsByEditionRow, error) {
	rows, err := q.db.Query(ctx, listTeamsByEdition, editionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamsByEditionRow
	for rows.Next() {
		var i ListTeamsByEditionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.LogoUrl,
			&i.PrimaryColor,
			&i.CreatedAt,
			&i.EditionTeamID,
			&i.Seed,
			&i.FinalPlacement,
			&i.Wins,
			&i.Losses,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFinalPlacement = `-- name: SetFinalPlacement :one
UPDATE edition_teams SET final_placement = $2 WHERE id = $1 RETURNING id, edition_id, team_id, seed, final_placement, wins, losses, created_at
`

type SetFinalPlacementParams struct {
	ID             pgtype.UUID `json:"id"`
	FinalPlacement *int32      `json:"final_placement"`
}

func (q *Queries) SetFinalPlacement(ctx context.Context, arg SetFinalPlacementParams) (EditionTeam, error) {
	row := q.db.QueryRow(ctx, setFinalPlacement, arg.ID, arg.FinalPlacement)
	var i EditionTeam
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.TeamID,
		&i.Seed,
		&i.FinalPlacement,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
	)
	return i, err
}

const updateEditionTeamStats = `-- name: UpdateEditionTeamStats :one
UPDATE edition_teams
SET wins = wins + $2, losses = losses + $3
WHERE id = $1
RETURNING id, edition_id, team_id, seed, final_placement, wins, losses, created_at
`

type UpdateEditionTeamStatsParams struct {
	ID     pgtype.UUID `json:"id"`
	Wins   int32       `json:"wins"`
	Losses int32       `json:"losses"`
}

func (q *Queries) UpdateEditionTeamStats(ctx context.Context, arg UpdateEditionTeamStatsParams) (EditionTeam, error) {
	row := q.db.QueryRow(ctx, updateEditionTeamStats, arg.ID, arg.Wins, arg.Losses)
	var i EditionTeam
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.TeamID,
		&i.Seed,
		&i.FinalPlacement,
		&i.Wins,
		&i.Losses,
		&i.CreatedAt,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams SET name = $2, logo_url = $3, primary_color = $4 WHERE id = $1 RETURNING id, name, slug, logo_url, primary_color, created_at
`

type UpdateTeamParams struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	LogoUrl      *string     `json:"logo_url"`
	PrimaryColor *string     `json:"primary_color"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.LogoUrl,
		arg.PrimaryColor,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.LogoUrl,
		&i.PrimaryColor,
		&i.CreatedAt,
	)
	return i, err
}
