package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/sg/unaerp-api/internal/db/seed"
	db "github.com/sg/unaerp-api/internal/db/sqlc"
	"github.com/sg/unaerp-api/internal/graph/generated"
	"github.com/sg/unaerp-api/internal/graph/model"
	"github.com/sg/unaerp-api/internal/middleware"
)

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, slug string, name string, coverURL *string) (*model.Game, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}
	g, err := r.DB.CreateGame(ctx, db.CreateGameParams{
		Slug:     slug,
		Name:     name,
		CoverUrl: coverURL,
		Active:   true,
	})
	if err != nil {
		return nil, err
	}
	return gameToModel(g), nil
}

// CreateEdition is the resolver for the createEdition field.
func (r *mutationResolver) CreateEdition(ctx context.Context, gameID uuid.UUID, year int, name string) (*model.Edition, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}
	e, err := r.DB.CreateEdition(ctx, db.CreateEditionParams{
		GameID:    gameID,
		Year:      int32(year),
		Name:      name,
		Status:    "draft",
		StartedAt: pgtype.Timestamptz{Valid: false},
	})
	if err != nil {
		return nil, err
	}

	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}

	return editionToModel(e, gameToModel(game)), nil
}

// UpdateEditionStatus is the resolver for the updateEditionStatus field.
func (r *mutationResolver) UpdateEditionStatus(ctx context.Context, id uuid.UUID, status string) (*model.Edition, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	// Set ended_at only when finishing
	var endedAt pgtype.Timestamptz
	if status == "finished" {
		endedAt = pgtype.Timestamptz{Time: time.Now(), Valid: true}
	}

	e, err := r.DB.UpdateEditionStatus(ctx, db.UpdateEditionStatusParams{
		ID:      id,
		Status:  status,
		EndedAt: endedAt,
	})
	if err != nil {
		return nil, err
	}

	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	if r.Redis != nil {
		_ = r.Redis.Del(ctx, fmt.Sprintf("active_edition:%s", game.Slug))
	}
	return editionToModel(e, gameToModel(game)), nil
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, name string, slug string, logoURL *string, primaryColor *string) (*model.Team, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}
	t, err := r.DB.CreateTeam(ctx, db.CreateTeamParams{
		Name:         name,
		Slug:         slug,
		LogoUrl:      logoURL,
		PrimaryColor: primaryColor,
	})
	if err != nil {
		return nil, err
	}
	return teamToModel(t), nil
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, id uuid.UUID, name string, logoURL *string, primaryColor *string) (*model.Team, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}
	t, err := r.DB.UpdateTeam(ctx, db.UpdateTeamParams{
		ID:           id,
		Name:         name,
		LogoUrl:      logoURL,
		PrimaryColor: primaryColor,
	})
	if err != nil {
		return nil, err
	}
	return teamToModel(t), nil
}

// AddTeamToEdition is the resolver for the addTeamToEdition field.
func (r *mutationResolver) AddTeamToEdition(ctx context.Context, editionID uuid.UUID, teamID uuid.UUID, seed *int) (*model.EditionTeam, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	var seedI32 *int32
	if seed != nil {
		v := int32(*seed)
		seedI32 = &v
	}

	et, err := r.DB.AddTeamToEdition(ctx, db.AddTeamToEditionParams{
		EditionID: editionID,
		TeamID:    teamID,
		Seed:      seedI32,
	})
	if err != nil {
		return nil, err
	}

	// invalidate standings cache
	if r.Redis != nil {
		_ = r.Redis.Del(ctx, fmt.Sprintf("standings:%s", editionID))
	}

	// fetch edition and team for nested fields
	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	// No GetTeamByID sqlc query — build stub Team with ID only.
	teamModel := &model.Team{ID: et.TeamID}

	return &model.EditionTeam{
		ID:             et.ID,
		Team:           teamModel,
		Edition:        editionModel,
		Seed:           int32PtrToIntPtr(et.Seed),
		FinalPlacement: int32PtrToIntPtr(et.FinalPlacement),
		Wins:           int(et.Wins),
		Losses:         int(et.Losses),
		Roster:         []*model.RosterEntry{},
	}, nil
}

// CreatePlayer is the resolver for the createPlayer field.
func (r *mutationResolver) CreatePlayer(ctx context.Context, ign string, sgaUserID *int, avatarURL *string, role *string) (*model.Player, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	var sgaID *int32
	if sgaUserID != nil {
		v := int32(*sgaUserID)
		sgaID = &v
	}

	p, err := r.DB.CreatePlayer(ctx, db.CreatePlayerParams{
		SgaUserID: sgaID,
		Ign:       ign,
		AvatarUrl: avatarURL,
		Role:      role,
	})
	if err != nil {
		return nil, err
	}
	return playerToModel(p), nil
}

// AddPlayerToRoster is the resolver for the addPlayerToRoster field.
func (r *mutationResolver) AddPlayerToRoster(ctx context.Context, editionTeamID uuid.UUID, playerID uuid.UUID, isCaptain *bool) (*model.RosterEntry, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	captain := false
	if isCaptain != nil {
		captain = *isCaptain
	}

	_, err := r.DB.AddPlayerToRoster(ctx, db.AddPlayerToRosterParams{
		EditionTeamID: editionTeamID,
		PlayerID:      playerID,
		IsCaptain:     captain,
	})
	if err != nil {
		return nil, err
	}

	// fetch player for nested field
	p, err := r.DB.GetPlayerByID(ctx, playerID)
	if err != nil {
		return nil, err
	}

	return &model.RosterEntry{
		Player:    playerToModel(p),
		IsCaptain: captain,
	}, nil
}

// CreateMatch is the resolver for the createMatch field.
func (r *mutationResolver) CreateMatch(ctx context.Context, editionID uuid.UUID, teamAId uuid.UUID, teamBId uuid.UUID, round string, scheduledAt *time.Time) (*model.Match, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	var scheduledTS pgtype.Timestamptz
	if scheduledAt != nil {
		scheduledTS = pgtype.Timestamptz{Time: *scheduledAt, Valid: true}
	}

	m, err := r.DB.CreateMatch(ctx, db.CreateMatchParams{
		EditionID:   editionID,
		TeamAID:     teamAId,
		TeamBID:     teamBId,
		Round:       round,
		ScheduledAt: scheduledTS,
	})
	if err != nil {
		return nil, err
	}

	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	// Stub edition teams with IDs only — full eager load not needed here
	teamA := &model.EditionTeam{ID: teamAId}
	teamB := &model.EditionTeam{ID: teamBId}

	return &model.Match{
		ID:          m.ID,
		Edition:     editionModel,
		TeamA:       teamA,
		TeamB:       teamB,
		Round:       m.Round,
		ScheduledAt: tsToPtr(m.ScheduledAt),
		Status:      m.Status,
		Result:      nil,
	}, nil
}

// RecordResult is the resolver for the recordResult field.
func (r *mutationResolver) RecordResult(ctx context.Context, matchID uuid.UUID, winnerID uuid.UUID, mapArg *string, scoreA int, scoreB int) (*model.MatchResult, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	tx, err := r.Pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	qtx := r.DB.WithTx(tx)

	// 1. Insert match result
	result, err := qtx.RecordMatchResult(ctx, db.RecordMatchResultParams{
		MatchID:  matchID,
		WinnerID: winnerID,
		Map:      mapArg,
		ScoreA:   int32(scoreA),
		ScoreB:   int32(scoreB),
		PlayedAt: pgtype.Timestamptz{Time: time.Now(), Valid: true},
	})
	if err != nil {
		return nil, err
	}

	// 2. Update match status to done
	_, err = qtx.UpdateMatchStatus(ctx, db.UpdateMatchStatusParams{
		ID:     matchID,
		Status: "done",
	})
	if err != nil {
		return nil, err
	}

	// 3. Get match details for edition_id (cache invalidation) and team IDs.
	// match.TeamAID / TeamBID are FKs to edition_teams.id — they are already edition_team_ids.
	match, err := qtx.GetMatchByID(ctx, matchID)
	if err != nil {
		return nil, err
	}

	// 4. Determine wins/losses increments.
	// winnerID is also an edition_team_id, so compare directly against match.TeamAID.
	winnerIsTeamA := winnerID == match.TeamAID
	aWins, aLosses := int32(0), int32(1)
	bWins, bLosses := int32(1), int32(0)
	if winnerIsTeamA {
		aWins, aLosses = 1, 0
		bWins, bLosses = 0, 1
	}

	_, err = qtx.UpdateEditionTeamStats(ctx, db.UpdateEditionTeamStatsParams{
		ID:     match.TeamAID,
		Wins:   aWins,
		Losses: aLosses,
	})
	if err != nil {
		return nil, err
	}
	_, err = qtx.UpdateEditionTeamStats(ctx, db.UpdateEditionTeamStatsParams{
		ID:     match.TeamBID,
		Wins:   bWins,
		Losses: bLosses,
	})
	if err != nil {
		return nil, err
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	// invalidate standings cache (outside transaction)
	if r.Redis != nil {
		_ = r.Redis.Del(ctx, fmt.Sprintf("standings:%s", match.EditionID))
	}

	// build winner EditionTeam stub with ID only
	winner := &model.EditionTeam{ID: winnerID}

	return &model.MatchResult{
		ID:       result.ID,
		Winner:   winner,
		Map:      result.Map,
		ScoreA:   int(result.ScoreA),
		ScoreB:   int(result.ScoreB),
		PlayedAt: tsToTime(result.PlayedAt),
	}, nil
}

// UploadMediaPresignedURL is the resolver for the uploadMediaPresignedUrl field.
func (r *mutationResolver) UploadMediaPresignedURL(ctx context.Context, editionID uuid.UUID, matchID *uuid.UUID, fileType string, mediaType string) (*model.PresignedUpload, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	key := fmt.Sprintf("unaerp/%s/%s/%s.%s",
		editionID,
		mediaType,
		uuid.New().String(),
		fileType,
	)

	contentType := "image/" + fileType
	uploadURL, err := r.R2.PresignUpload(ctx, key, contentType)
	if err != nil {
		return nil, err
	}

	return &model.PresignedUpload{
		UploadURL: uploadURL,
		PublicURL: r.R2.PublicURL(key),
		R2Key:     key,
	}, nil
}

// ConfirmMediaUpload is the resolver for the confirmMediaUpload field.
func (r *mutationResolver) ConfirmMediaUpload(ctx context.Context, editionID uuid.UUID, matchID *uuid.UUID, r2Key string, url string, caption *string, mediaType string) (*model.Media, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}
	row, err := r.DB.CreateMedia(ctx, db.CreateMediaParams{
		EditionID: editionID,
		MatchID:   matchID,
		R2Key:     r2Key,
		Url:       url,
		Caption:   caption,
		Type:      mediaType,
	})
	if err != nil {
		return nil, err
	}
	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))
	return mediaToModel(row, editionModel), nil
}

// CreateHighlight is the resolver for the createHighlight field.
func (r *mutationResolver) CreateHighlight(ctx context.Context, editionID uuid.UUID, matchID *uuid.UUID, cfStreamID string, title string, thumbnailURL *string) (*model.Highlight, error) {
	if err := requireAuth(ctx); err != nil {
		return nil, err
	}

	h, err := r.DB.CreateHighlight(ctx, db.CreateHighlightParams{
		EditionID:    editionID,
		MatchID:      matchID,
		CfStreamID:   cfStreamID,
		Title:        title,
		ThumbnailUrl: thumbnailURL,
		PublishedAt:  pgtype.Timestamptz{Time: time.Now(), Valid: true},
	})
	if err != nil {
		return nil, err
	}

	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	return highlightToModel(h, editionModel), nil
}

// ImportEdition is the resolver for the importEdition field.
func (r *mutationResolver) ImportEdition(ctx context.Context, payload string) (bool, error) {
	if err := requireAuth(ctx); err != nil {
		return false, err
	}

	data, err := seed.ParseImport(payload)
	if err != nil {
		return false, fmt.Errorf("payload inválido: %w", err)
	}

	if err := seed.Import(ctx, r.DB, data); err != nil {
		return false, err
	}

	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Me, error) {
	u := middleware.UserFromContext(ctx)
	if u == nil {
		return nil, nil
	}
	return &model.Me{
		UserID: u.UserID,
		Email:  u.Email,
		Login:  u.Login,
		Role:   u.Role,
	}, nil
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context) ([]*model.Game, error) {
	rows, err := r.DB.ListGames(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Game, 0, len(rows))
	for _, g := range rows {
		result = append(result, gameToModel(g))
	}
	return result, nil
}

// ActiveEdition is the resolver for the activeEdition field.
func (r *queryResolver) ActiveEdition(ctx context.Context, gameSlug string) (*model.Edition, error) {
	cacheKey := "active_edition:" + gameSlug

	// try cache
	if r.Redis != nil {
		cached, err := r.Redis.Get(ctx, cacheKey).Bytes()
		if err == nil {
			var m model.Edition
			if jsonErr := json.Unmarshal(cached, &m); jsonErr == nil {
				return &m, nil
			}
		}
	}

	e, err := r.DB.GetActiveEdition(ctx, gameSlug)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	game, err := r.DB.GetGameBySlug(ctx, gameSlug)
	if err != nil && !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	var gameModel *model.Game
	if err == nil {
		gameModel = gameToModel(game)
	}

	result := editionToModel(e, gameModel)

	// write to cache
	if r.Redis != nil {
		if data, jsonErr := json.Marshal(result); jsonErr == nil {
			r.Redis.Set(ctx, cacheKey, data, 30*time.Second)
		}
	}

	return result, nil
}

// Edition is the resolver for the edition field.
func (r *queryResolver) Edition(ctx context.Context, id uuid.UUID) (*model.Edition, error) {
	e, err := r.DB.GetEditionByID(ctx, id)
	if err != nil {
		return nil, err
	}

	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}

	return editionToModel(e, gameToModel(game)), nil
}

// Editions is the resolver for the editions field.
func (r *queryResolver) Editions(ctx context.Context, gameSlug string) ([]*model.Edition, error) {
	game, err := r.DB.GetGameBySlug(ctx, gameSlug)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return []*model.Edition{}, nil
		}
		return nil, err
	}
	gameModel := gameToModel(game)

	rows, err := r.DB.ListEditionsByGame(ctx, game.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Edition, 0, len(rows))
	for _, e := range rows {
		result = append(result, editionToModel(e, gameModel))
	}
	return result, nil
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, editionID uuid.UUID) ([]*model.EditionTeam, error) {
	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	rows, err := r.DB.ListTeamsByEdition(ctx, editionID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.EditionTeam, 0, len(rows))
	for _, row := range rows {
		result = append(result, editionTeamFromRow(row, editionModel))
	}
	return result, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, slug string) (*model.Team, error) {
	t, err := r.DB.GetTeamBySlug(ctx, slug)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}
	return teamToModel(t), nil
}

// Standings is the resolver for the standings field.
func (r *queryResolver) Standings(ctx context.Context, editionID uuid.UUID) ([]*model.Standing, error) {
	cacheKey := fmt.Sprintf("standings:%s", editionID.String())

	// try cache
	if r.Redis != nil {
		cached, err := r.Redis.Get(ctx, cacheKey).Bytes()
		if err == nil {
			var standings []*model.Standing
			if jsonErr := json.Unmarshal(cached, &standings); jsonErr == nil {
				return standings, nil
			}
		}
	}

	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	rows, err := r.DB.ListTeamsByEdition(ctx, editionID)
	if err != nil {
		return nil, err
	}

	standings := make([]*model.Standing, 0, len(rows))
	for _, row := range rows {
		et := editionTeamFromRow(row, editionModel)
		standings = append(standings, &model.Standing{
			EditionTeam:    et,
			Wins:           int(row.Wins),
			Losses:         int(row.Losses),
			FinalPlacement: int32PtrToIntPtr(row.FinalPlacement),
		})
	}

	// write to cache
	if r.Redis != nil {
		if data, jsonErr := json.Marshal(standings); jsonErr == nil {
			r.Redis.Set(ctx, cacheKey, data, 30*time.Second)
		}
	}

	return standings, nil
}

// Matches is the resolver for the matches field.
func (r *queryResolver) Matches(ctx context.Context, editionID uuid.UUID, round *string) ([]*model.Match, error) {
	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	// pre-fetch teams for this edition to resolve teamA/teamB
	teamRows, err := r.DB.ListTeamsByEdition(ctx, editionID)
	if err != nil {
		return nil, err
	}
	// build map keyed by edition_team_id (matches.team_a_id/team_b_id are FKs to edition_teams.id)
	etByEditionTeamID := make(map[uuid.UUID]*model.EditionTeam, len(teamRows))
	for _, tr := range teamRows {
		et := editionTeamFromRow(tr, editionModel)
		etByEditionTeamID[tr.EditionTeamID] = et
	}

	rows, err := r.DB.ListMatchesByEdition(ctx, editionID)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Match, 0, len(rows))
	for _, row := range rows {
		if round != nil && row.Round != *round {
			continue
		}

		teamA := etByEditionTeamID[row.TeamAID]
		teamB := etByEditionTeamID[row.TeamBID]

		var matchResult *model.MatchResult
		if row.WinnerID != nil {
			winner := etByEditionTeamID[*row.WinnerID]
			matchResult = matchResultFromListRow(row, winner)
		}

		result = append(result, matchFromListRow(row, editionModel, teamA, teamB, matchResult))
	}
	return result, nil
}

// Match is the resolver for the match field.
func (r *queryResolver) Match(ctx context.Context, id uuid.UUID) (*model.Match, error) {
	row, err := r.DB.GetMatchByID(ctx, id)
	if err != nil {
		return nil, err
	}

	e, err := r.DB.GetEditionByID(ctx, row.EditionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	// pre-fetch teams; key by edition_team_id (matches.team_a_id/team_b_id are FKs to edition_teams.id)
	teamRows, err := r.DB.ListTeamsByEdition(ctx, row.EditionID)
	if err != nil {
		return nil, err
	}
	etByEditionTeamID := make(map[uuid.UUID]*model.EditionTeam, len(teamRows))
	for _, tr := range teamRows {
		et := editionTeamFromRow(tr, editionModel)
		etByEditionTeamID[tr.EditionTeamID] = et
	}

	teamA := etByEditionTeamID[row.TeamAID]
	teamB := etByEditionTeamID[row.TeamBID]

	var matchResult *model.MatchResult
	if row.WinnerID != nil {
		winner := etByEditionTeamID[*row.WinnerID]
		matchResult = matchResultFromGetRow(row, winner)
	}

	return matchFromGetRow(row, editionModel, teamA, teamB, matchResult), nil
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id uuid.UUID) (*model.Player, error) {
	p, err := r.DB.GetPlayerByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return playerToModel(p), nil
}

// Highlights is the resolver for the highlights field.
func (r *queryResolver) Highlights(ctx context.Context, editionID uuid.UUID) ([]*model.Highlight, error) {
	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	rows, err := r.DB.ListHighlightsByEdition(ctx, editionID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Highlight, 0, len(rows))
	for _, h := range rows {
		result = append(result, highlightToModel(h, editionModel))
	}
	return result, nil
}

// Gallery is the resolver for the gallery field.
func (r *queryResolver) Gallery(ctx context.Context, editionID uuid.UUID) ([]*model.Media, error) {
	e, err := r.DB.GetEditionByID(ctx, editionID)
	if err != nil {
		return nil, err
	}
	game, err := r.DB.GetGameByID(ctx, e.GameID)
	if err != nil {
		return nil, err
	}
	editionModel := editionToModel(e, gameToModel(game))

	rows, err := r.DB.ListMediaByEdition(ctx, db.ListMediaByEditionParams{
		EditionID: editionID,
		Type:      "photo",
	})
	if err != nil {
		return nil, err
	}
	result := make([]*model.Media, 0, len(rows))
	for _, m := range rows {
		result = append(result, mediaToModel(m, editionModel))
	}
	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
