package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sg/unaerp-api/internal/graph/generated"
	"github.com/sg/unaerp-api/internal/graph/model"
)

// CreateGame is the resolver for the createGame field.
func (r *mutationResolver) CreateGame(ctx context.Context, slug string, name string, coverURL *string) (*model.Game, error) {
	panic(fmt.Errorf("not implemented: CreateGame - createGame"))
}

// CreateEdition is the resolver for the createEdition field.
func (r *mutationResolver) CreateEdition(ctx context.Context, gameID uuid.UUID, year int, name string) (*model.Edition, error) {
	panic(fmt.Errorf("not implemented: CreateEdition - createEdition"))
}

// UpdateEditionStatus is the resolver for the updateEditionStatus field.
func (r *mutationResolver) UpdateEditionStatus(ctx context.Context, id uuid.UUID, status string) (*model.Edition, error) {
	panic(fmt.Errorf("not implemented: UpdateEditionStatus - updateEditionStatus"))
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, name string, slug string, logoURL *string, primaryColor *string) (*model.Team, error) {
	panic(fmt.Errorf("not implemented: CreateTeam - createTeam"))
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, id uuid.UUID, name string, logoURL *string, primaryColor *string) (*model.Team, error) {
	panic(fmt.Errorf("not implemented: UpdateTeam - updateTeam"))
}

// AddTeamToEdition is the resolver for the addTeamToEdition field.
func (r *mutationResolver) AddTeamToEdition(ctx context.Context, editionID uuid.UUID, teamID uuid.UUID, seed *int) (*model.EditionTeam, error) {
	panic(fmt.Errorf("not implemented: AddTeamToEdition - addTeamToEdition"))
}

// CreatePlayer is the resolver for the createPlayer field.
func (r *mutationResolver) CreatePlayer(ctx context.Context, ign string, sgaUserID *int, avatarURL *string, role *string) (*model.Player, error) {
	panic(fmt.Errorf("not implemented: CreatePlayer - createPlayer"))
}

// AddPlayerToRoster is the resolver for the addPlayerToRoster field.
func (r *mutationResolver) AddPlayerToRoster(ctx context.Context, editionTeamID uuid.UUID, playerID uuid.UUID, isCaptain *bool) (*model.RosterEntry, error) {
	panic(fmt.Errorf("not implemented: AddPlayerToRoster - addPlayerToRoster"))
}

// CreateMatch is the resolver for the createMatch field.
func (r *mutationResolver) CreateMatch(ctx context.Context, editionID uuid.UUID, teamAId uuid.UUID, teamBId uuid.UUID, round string, scheduledAt *time.Time) (*model.Match, error) {
	panic(fmt.Errorf("not implemented: CreateMatch - createMatch"))
}

// RecordResult is the resolver for the recordResult field.
func (r *mutationResolver) RecordResult(ctx context.Context, matchID uuid.UUID, winnerID uuid.UUID, mapArg *string, scoreA int, scoreB int) (*model.MatchResult, error) {
	panic(fmt.Errorf("not implemented: RecordResult - recordResult"))
}

// UploadMediaPresignedURL is the resolver for the uploadMediaPresignedUrl field.
func (r *mutationResolver) UploadMediaPresignedURL(ctx context.Context, editionID uuid.UUID, matchID *uuid.UUID, fileType string, mediaType string) (*model.PresignedUpload, error) {
	panic(fmt.Errorf("not implemented: UploadMediaPresignedURL - uploadMediaPresignedUrl"))
}

// ConfirmMediaUpload is the resolver for the confirmMediaUpload field.
func (r *mutationResolver) ConfirmMediaUpload(ctx context.Context, editionID uuid.UUID, matchID *uuid.UUID, r2Key string, url string, caption *string, mediaType string) (*model.Media, error) {
	panic(fmt.Errorf("not implemented: ConfirmMediaUpload - confirmMediaUpload"))
}

// CreateHighlight is the resolver for the createHighlight field.
func (r *mutationResolver) CreateHighlight(ctx context.Context, editionID uuid.UUID, matchID *uuid.UUID, cfStreamID string, title string, thumbnailURL *string) (*model.Highlight, error) {
	panic(fmt.Errorf("not implemented: CreateHighlight - createHighlight"))
}

// ImportEdition is the resolver for the importEdition field.
func (r *mutationResolver) ImportEdition(ctx context.Context, payload string) (bool, error) {
	panic(fmt.Errorf("not implemented: ImportEdition - importEdition"))
}

// Games is the resolver for the games field.
func (r *queryResolver) Games(ctx context.Context) ([]*model.Game, error) {
	panic(fmt.Errorf("not implemented: Games - games"))
}

// ActiveEdition is the resolver for the activeEdition field.
func (r *queryResolver) ActiveEdition(ctx context.Context, gameSlug string) (*model.Edition, error) {
	panic(fmt.Errorf("not implemented: ActiveEdition - activeEdition"))
}

// Edition is the resolver for the edition field.
func (r *queryResolver) Edition(ctx context.Context, id uuid.UUID) (*model.Edition, error) {
	panic(fmt.Errorf("not implemented: Edition - edition"))
}

// Editions is the resolver for the editions field.
func (r *queryResolver) Editions(ctx context.Context, gameSlug string) ([]*model.Edition, error) {
	panic(fmt.Errorf("not implemented: Editions - editions"))
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, editionID uuid.UUID) ([]*model.EditionTeam, error) {
	panic(fmt.Errorf("not implemented: Teams - teams"))
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, slug string) (*model.Team, error) {
	panic(fmt.Errorf("not implemented: Team - team"))
}

// Standings is the resolver for the standings field.
func (r *queryResolver) Standings(ctx context.Context, editionID uuid.UUID) ([]*model.Standing, error) {
	panic(fmt.Errorf("not implemented: Standings - standings"))
}

// Matches is the resolver for the matches field.
func (r *queryResolver) Matches(ctx context.Context, editionID uuid.UUID, round *string) ([]*model.Match, error) {
	panic(fmt.Errorf("not implemented: Matches - matches"))
}

// Match is the resolver for the match field.
func (r *queryResolver) Match(ctx context.Context, id uuid.UUID) (*model.Match, error) {
	panic(fmt.Errorf("not implemented: Match - match"))
}

// Player is the resolver for the player field.
func (r *queryResolver) Player(ctx context.Context, id uuid.UUID) (*model.Player, error) {
	panic(fmt.Errorf("not implemented: Player - player"))
}

// Highlights is the resolver for the highlights field.
func (r *queryResolver) Highlights(ctx context.Context, editionID uuid.UUID) ([]*model.Highlight, error) {
	panic(fmt.Errorf("not implemented: Highlights - highlights"))
}

// Gallery is the resolver for the gallery field.
func (r *queryResolver) Gallery(ctx context.Context, editionID uuid.UUID) ([]*model.Media, error) {
	panic(fmt.Errorf("not implemented: Gallery - gallery"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
