/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesIndexRouteImport } from './routes/times/index'
import { Route as JogadoresIndexRouteImport } from './routes/jogadores/index'
import { Route as EdicoesIndexRouteImport } from './routes/edicoes/index'
import { Route as ConfrontosIndexRouteImport } from './routes/confrontos/index'
import { Route as TimesSlugRouteImport } from './routes/times/$slug'
import { Route as JogadoresIdRouteImport } from './routes/jogadores/$id'
import { Route as EdicoesYearRouteImport } from './routes/edicoes/$year'
import { Route as ConfrontosIdRouteImport } from './routes/confrontos/$id'

const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesIndexRoute = TimesIndexRouteImport.update({
  id: '/times/',
  path: '/times/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIndexRoute = JogadoresIndexRouteImport.update({
  id: '/jogadores/',
  path: '/jogadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesIndexRoute = EdicoesIndexRouteImport.update({
  id: '/edicoes/',
  path: '/edicoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfrontosIndexRoute = ConfrontosIndexRouteImport.update({
  id: '/confrontos/',
  path: '/confrontos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesSlugRoute = TimesSlugRouteImport.update({
  id: '/times/$slug',
  path: '/times/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIdRoute = JogadoresIdRouteImport.update({
  id: '/jogadores/$id',
  path: '/jogadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesYearRoute = EdicoesYearRouteImport.update({
  id: '/edicoes/$year',
  path: '/edicoes/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfrontosIdRoute = ConfrontosIdRouteImport.update({
  id: '/confrontos/$id',
  path: '/confrontos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/galeria': typeof GaleriaRoute
  '/highlights': typeof HighlightsRoute
  '/confrontos/$id': typeof ConfrontosIdRoute
  '/edicoes/$year': typeof EdicoesYearRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/confrontos/': typeof ConfrontosIndexRoute
  '/edicoes/': typeof EdicoesIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
  '/times/': typeof TimesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/galeria': typeof GaleriaRoute
  '/highlights': typeof HighlightsRoute
  '/confrontos/$id': typeof ConfrontosIdRoute
  '/edicoes/$year': typeof EdicoesYearRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/confrontos': typeof ConfrontosIndexRoute
  '/edicoes': typeof EdicoesIndexRoute
  '/jogadores': typeof JogadoresIndexRoute
  '/times': typeof TimesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/galeria': typeof GaleriaRoute
  '/highlights': typeof HighlightsRoute
  '/confrontos/$id': typeof ConfrontosIdRoute
  '/edicoes/$year': typeof EdicoesYearRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/confrontos/': typeof ConfrontosIndexRoute
  '/edicoes/': typeof EdicoesIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
  '/times/': typeof TimesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classificacao'
    | '/galeria'
    | '/highlights'
    | '/confrontos/$id'
    | '/edicoes/$year'
    | '/jogadores/$id'
    | '/times/$slug'
    | '/confrontos/'
    | '/edicoes/'
    | '/jogadores/'
    | '/times/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classificacao'
    | '/galeria'
    | '/highlights'
    | '/confrontos/$id'
    | '/edicoes/$year'
    | '/jogadores/$id'
    | '/times/$slug'
    | '/confrontos'
    | '/edicoes'
    | '/jogadores'
    | '/times'
  id:
    | '__root__'
    | '/'
    | '/classificacao'
    | '/galeria'
    | '/highlights'
    | '/confrontos/$id'
    | '/edicoes/$year'
    | '/jogadores/$id'
    | '/times/$slug'
    | '/confrontos/'
    | '/edicoes/'
    | '/jogadores/'
    | '/times/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  GaleriaRoute: typeof GaleriaRoute
  HighlightsRoute: typeof HighlightsRoute
  ConfrontosIdRoute: typeof ConfrontosIdRoute
  EdicoesYearRoute: typeof EdicoesYearRoute
  JogadoresIdRoute: typeof JogadoresIdRoute
  TimesSlugRoute: typeof TimesSlugRoute
  ConfrontosIndexRoute: typeof ConfrontosIndexRoute
  EdicoesIndexRoute: typeof EdicoesIndexRoute
  JogadoresIndexRoute: typeof JogadoresIndexRoute
  TimesIndexRoute: typeof TimesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times/': {
      id: '/times/'
      path: '/times'
      fullPath: '/times/'
      preLoaderRoute: typeof TimesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/': {
      id: '/jogadores/'
      path: '/jogadores'
      fullPath: '/jogadores/'
      preLoaderRoute: typeof JogadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes/': {
      id: '/edicoes/'
      path: '/edicoes'
      fullPath: '/edicoes/'
      preLoaderRoute: typeof EdicoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confrontos/': {
      id: '/confrontos/'
      path: '/confrontos'
      fullPath: '/confrontos/'
      preLoaderRoute: typeof ConfrontosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times/$slug': {
      id: '/times/$slug'
      path: '/times/$slug'
      fullPath: '/times/$slug'
      preLoaderRoute: typeof TimesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/$id': {
      id: '/jogadores/$id'
      path: '/jogadores/$id'
      fullPath: '/jogadores/$id'
      preLoaderRoute: typeof JogadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes/$year': {
      id: '/edicoes/$year'
      path: '/edicoes/$year'
      fullPath: '/edicoes/$year'
      preLoaderRoute: typeof EdicoesYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confrontos/$id': {
      id: '/confrontos/$id'
      path: '/confrontos/$id'
      fullPath: '/confrontos/$id'
      preLoaderRoute: typeof ConfrontosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  GaleriaRoute: GaleriaRoute,
  HighlightsRoute: HighlightsRoute,
  ConfrontosIdRoute: ConfrontosIdRoute,
  EdicoesYearRoute: EdicoesYearRoute,
  JogadoresIdRoute: JogadoresIdRoute,
  TimesSlugRoute: TimesSlugRoute,
  ConfrontosIndexRoute: ConfrontosIndexRoute,
  EdicoesIndexRoute: EdicoesIndexRoute,
  JogadoresIndexRoute: JogadoresIndexRoute,
  TimesIndexRoute: TimesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
