/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HighlightsRouteImport } from './routes/highlights'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesIndexRouteImport } from './routes/times/index'
import { Route as JogadoresIndexRouteImport } from './routes/jogadores/index'
import { Route as EdicoesIndexRouteImport } from './routes/edicoes/index'
import { Route as ConfrontosIndexRouteImport } from './routes/confrontos/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TimesSlugRouteImport } from './routes/times/$slug'
import { Route as JogadoresIdRouteImport } from './routes/jogadores/$id'
import { Route as EdicoesYearRouteImport } from './routes/edicoes/$year'
import { Route as ConfrontosIdRouteImport } from './routes/confrontos/$id'
import { Route as AdminTimesRouteImport } from './routes/admin/times'
import { Route as AdminMidiaRouteImport } from './routes/admin/midia'
import { Route as AdminJogadoresRouteImport } from './routes/admin/jogadores'
import { Route as AdminImportarRouteImport } from './routes/admin/importar'
import { Route as AdminHighlightsRouteImport } from './routes/admin/highlights'
import { Route as AdminEdicoesRouteImport } from './routes/admin/edicoes'
import { Route as AdminConfrontosRouteImport } from './routes/admin/confrontos'

const HighlightsRoute = HighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesIndexRoute = TimesIndexRouteImport.update({
  id: '/times/',
  path: '/times/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIndexRoute = JogadoresIndexRouteImport.update({
  id: '/jogadores/',
  path: '/jogadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesIndexRoute = EdicoesIndexRouteImport.update({
  id: '/edicoes/',
  path: '/edicoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfrontosIndexRoute = ConfrontosIndexRouteImport.update({
  id: '/confrontos/',
  path: '/confrontos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TimesSlugRoute = TimesSlugRouteImport.update({
  id: '/times/$slug',
  path: '/times/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresIdRoute = JogadoresIdRouteImport.update({
  id: '/jogadores/$id',
  path: '/jogadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicoesYearRoute = EdicoesYearRouteImport.update({
  id: '/edicoes/$year',
  path: '/edicoes/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfrontosIdRoute = ConfrontosIdRouteImport.update({
  id: '/confrontos/$id',
  path: '/confrontos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTimesRoute = AdminTimesRouteImport.update({
  id: '/times',
  path: '/times',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMidiaRoute = AdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminJogadoresRoute = AdminJogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportarRoute = AdminImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHighlightsRoute = AdminHighlightsRouteImport.update({
  id: '/highlights',
  path: '/highlights',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEdicoesRoute = AdminEdicoesRouteImport.update({
  id: '/edicoes',
  path: '/edicoes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfrontosRoute = AdminConfrontosRouteImport.update({
  id: '/confrontos',
  path: '/confrontos',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/classificacao': typeof ClassificacaoRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/highlights': typeof HighlightsRoute
  '/admin/confrontos': typeof AdminConfrontosRoute
  '/admin/edicoes': typeof AdminEdicoesRoute
  '/admin/highlights': typeof AdminHighlightsRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/times': typeof AdminTimesRoute
  '/confrontos/$id': typeof ConfrontosIdRoute
  '/edicoes/$year': typeof EdicoesYearRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/confrontos/': typeof ConfrontosIndexRoute
  '/edicoes/': typeof EdicoesIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
  '/times/': typeof TimesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificacao': typeof ClassificacaoRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/highlights': typeof HighlightsRoute
  '/admin/confrontos': typeof AdminConfrontosRoute
  '/admin/edicoes': typeof AdminEdicoesRoute
  '/admin/highlights': typeof AdminHighlightsRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/times': typeof AdminTimesRoute
  '/confrontos/$id': typeof ConfrontosIdRoute
  '/edicoes/$year': typeof EdicoesYearRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/confrontos': typeof ConfrontosIndexRoute
  '/edicoes': typeof EdicoesIndexRoute
  '/jogadores': typeof JogadoresIndexRoute
  '/times': typeof TimesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/classificacao': typeof ClassificacaoRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/highlights': typeof HighlightsRoute
  '/admin/confrontos': typeof AdminConfrontosRoute
  '/admin/edicoes': typeof AdminEdicoesRoute
  '/admin/highlights': typeof AdminHighlightsRoute
  '/admin/importar': typeof AdminImportarRoute
  '/admin/jogadores': typeof AdminJogadoresRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/times': typeof AdminTimesRoute
  '/confrontos/$id': typeof ConfrontosIdRoute
  '/edicoes/$year': typeof EdicoesYearRoute
  '/jogadores/$id': typeof JogadoresIdRoute
  '/times/$slug': typeof TimesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/confrontos/': typeof ConfrontosIndexRoute
  '/edicoes/': typeof EdicoesIndexRoute
  '/jogadores/': typeof JogadoresIndexRoute
  '/times/': typeof TimesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/classificacao'
    | '/entrar'
    | '/galeria'
    | '/highlights'
    | '/admin/confrontos'
    | '/admin/edicoes'
    | '/admin/highlights'
    | '/admin/importar'
    | '/admin/jogadores'
    | '/admin/midia'
    | '/admin/times'
    | '/confrontos/$id'
    | '/edicoes/$year'
    | '/jogadores/$id'
    | '/times/$slug'
    | '/admin/'
    | '/confrontos/'
    | '/edicoes/'
    | '/jogadores/'
    | '/times/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classificacao'
    | '/entrar'
    | '/galeria'
    | '/highlights'
    | '/admin/confrontos'
    | '/admin/edicoes'
    | '/admin/highlights'
    | '/admin/importar'
    | '/admin/jogadores'
    | '/admin/midia'
    | '/admin/times'
    | '/confrontos/$id'
    | '/edicoes/$year'
    | '/jogadores/$id'
    | '/times/$slug'
    | '/admin'
    | '/confrontos'
    | '/edicoes'
    | '/jogadores'
    | '/times'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/classificacao'
    | '/entrar'
    | '/galeria'
    | '/highlights'
    | '/admin/confrontos'
    | '/admin/edicoes'
    | '/admin/highlights'
    | '/admin/importar'
    | '/admin/jogadores'
    | '/admin/midia'
    | '/admin/times'
    | '/confrontos/$id'
    | '/edicoes/$year'
    | '/jogadores/$id'
    | '/times/$slug'
    | '/admin/'
    | '/confrontos/'
    | '/edicoes/'
    | '/jogadores/'
    | '/times/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ClassificacaoRoute: typeof ClassificacaoRoute
  EntrarRoute: typeof EntrarRoute
  GaleriaRoute: typeof GaleriaRoute
  HighlightsRoute: typeof HighlightsRoute
  ConfrontosIdRoute: typeof ConfrontosIdRoute
  EdicoesYearRoute: typeof EdicoesYearRoute
  JogadoresIdRoute: typeof JogadoresIdRoute
  TimesSlugRoute: typeof TimesSlugRoute
  ConfrontosIndexRoute: typeof ConfrontosIndexRoute
  EdicoesIndexRoute: typeof EdicoesIndexRoute
  JogadoresIndexRoute: typeof JogadoresIndexRoute
  TimesIndexRoute: typeof TimesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/highlights': {
      id: '/highlights'
      path: '/highlights'
      fullPath: '/highlights'
      preLoaderRoute: typeof HighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times/': {
      id: '/times/'
      path: '/times'
      fullPath: '/times/'
      preLoaderRoute: typeof TimesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/': {
      id: '/jogadores/'
      path: '/jogadores'
      fullPath: '/jogadores/'
      preLoaderRoute: typeof JogadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes/': {
      id: '/edicoes/'
      path: '/edicoes'
      fullPath: '/edicoes/'
      preLoaderRoute: typeof EdicoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confrontos/': {
      id: '/confrontos/'
      path: '/confrontos'
      fullPath: '/confrontos/'
      preLoaderRoute: typeof ConfrontosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/times/$slug': {
      id: '/times/$slug'
      path: '/times/$slug'
      fullPath: '/times/$slug'
      preLoaderRoute: typeof TimesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/$id': {
      id: '/jogadores/$id'
      path: '/jogadores/$id'
      fullPath: '/jogadores/$id'
      preLoaderRoute: typeof JogadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicoes/$year': {
      id: '/edicoes/$year'
      path: '/edicoes/$year'
      fullPath: '/edicoes/$year'
      preLoaderRoute: typeof EdicoesYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confrontos/$id': {
      id: '/confrontos/$id'
      path: '/confrontos/$id'
      fullPath: '/confrontos/$id'
      preLoaderRoute: typeof ConfrontosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/times': {
      id: '/admin/times'
      path: '/times'
      fullPath: '/admin/times'
      preLoaderRoute: typeof AdminTimesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/midia': {
      id: '/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminMidiaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/jogadores': {
      id: '/admin/jogadores'
      path: '/jogadores'
      fullPath: '/admin/jogadores'
      preLoaderRoute: typeof AdminJogadoresRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/importar': {
      id: '/admin/importar'
      path: '/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AdminImportarRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/highlights': {
      id: '/admin/highlights'
      path: '/highlights'
      fullPath: '/admin/highlights'
      preLoaderRoute: typeof AdminHighlightsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/edicoes': {
      id: '/admin/edicoes'
      path: '/edicoes'
      fullPath: '/admin/edicoes'
      preLoaderRoute: typeof AdminEdicoesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/confrontos': {
      id: '/admin/confrontos'
      path: '/confrontos'
      fullPath: '/admin/confrontos'
      preLoaderRoute: typeof AdminConfrontosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminConfrontosRoute: typeof AdminConfrontosRoute
  AdminEdicoesRoute: typeof AdminEdicoesRoute
  AdminHighlightsRoute: typeof AdminHighlightsRoute
  AdminImportarRoute: typeof AdminImportarRoute
  AdminJogadoresRoute: typeof AdminJogadoresRoute
  AdminMidiaRoute: typeof AdminMidiaRoute
  AdminTimesRoute: typeof AdminTimesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminConfrontosRoute: AdminConfrontosRoute,
  AdminEdicoesRoute: AdminEdicoesRoute,
  AdminHighlightsRoute: AdminHighlightsRoute,
  AdminImportarRoute: AdminImportarRoute,
  AdminJogadoresRoute: AdminJogadoresRoute,
  AdminMidiaRoute: AdminMidiaRoute,
  AdminTimesRoute: AdminTimesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ClassificacaoRoute: ClassificacaoRoute,
  EntrarRoute: EntrarRoute,
  GaleriaRoute: GaleriaRoute,
  HighlightsRoute: HighlightsRoute,
  ConfrontosIdRoute: ConfrontosIdRoute,
  EdicoesYearRoute: EdicoesYearRoute,
  JogadoresIdRoute: JogadoresIdRoute,
  TimesSlugRoute: TimesSlugRoute,
  ConfrontosIndexRoute: ConfrontosIndexRoute,
  EdicoesIndexRoute: EdicoesIndexRoute,
  JogadoresIndexRoute: JogadoresIndexRoute,
  TimesIndexRoute: TimesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
