// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Edition struct {
	ID        uuid.UUID      `json:"id"`
	Game      *Game          `json:"game"`
	Year      int            `json:"year"`
	Name      string         `json:"name"`
	Status    string         `json:"status"`
	StartedAt *time.Time     `json:"startedAt,omitempty"`
	EndedAt   *time.Time     `json:"endedAt,omitempty"`
	Teams     []*EditionTeam `json:"teams"`
}

type EditionTeam struct {
	ID             uuid.UUID      `json:"id"`
	Team           *Team          `json:"team"`
	Edition        *Edition       `json:"edition"`
	Seed           *int           `json:"seed,omitempty"`
	FinalPlacement *int           `json:"finalPlacement,omitempty"`
	Wins           int            `json:"wins"`
	Losses         int            `json:"losses"`
	Roster         []*RosterEntry `json:"roster"`
}

type Game struct {
	ID       uuid.UUID `json:"id"`
	Slug     string    `json:"slug"`
	Name     string    `json:"name"`
	CoverURL *string   `json:"coverUrl,omitempty"`
	Active   bool      `json:"active"`
}

type Highlight struct {
	ID           uuid.UUID `json:"id"`
	Edition      *Edition  `json:"edition"`
	Match        *Match    `json:"match,omitempty"`
	CfStreamID   string    `json:"cfStreamId"`
	Title        string    `json:"title"`
	ThumbnailURL *string   `json:"thumbnailUrl,omitempty"`
	PublishedAt  time.Time `json:"publishedAt"`
}

type Match struct {
	ID          uuid.UUID    `json:"id"`
	Edition     *Edition     `json:"edition"`
	TeamA       *EditionTeam `json:"teamA"`
	TeamB       *EditionTeam `json:"teamB"`
	Round       string       `json:"round"`
	ScheduledAt *time.Time   `json:"scheduledAt,omitempty"`
	Status      string       `json:"status"`
	Result      *MatchResult `json:"result,omitempty"`
}

type MatchResult struct {
	ID       uuid.UUID    `json:"id"`
	Winner   *EditionTeam `json:"winner"`
	Map      *string      `json:"map,omitempty"`
	ScoreA   int          `json:"scoreA"`
	ScoreB   int          `json:"scoreB"`
	PlayedAt time.Time    `json:"playedAt"`
}

type Media struct {
	ID      uuid.UUID `json:"id"`
	Edition *Edition  `json:"edition"`
	Match   *Match    `json:"match,omitempty"`
	R2Key   string    `json:"r2Key"`
	URL     string    `json:"url"`
	Caption *string   `json:"caption,omitempty"`
	Type    string    `json:"type"`
}

type Mutation struct {
}

type Player struct {
	ID        uuid.UUID `json:"id"`
	SgaUserID *int      `json:"sgaUserId,omitempty"`
	Ign       string    `json:"ign"`
	AvatarURL *string   `json:"avatarUrl,omitempty"`
	Role      *string   `json:"role,omitempty"`
}

type PresignedUpload struct {
	UploadURL string `json:"uploadUrl"`
	PublicURL string `json:"publicUrl"`
	R2Key     string `json:"r2Key"`
}

type Query struct {
}

type RosterEntry struct {
	Player    *Player `json:"player"`
	IsCaptain bool    `json:"isCaptain"`
}

type Standing struct {
	EditionTeam    *EditionTeam `json:"editionTeam"`
	Wins           int          `json:"wins"`
	Losses         int          `json:"losses"`
	FinalPlacement *int         `json:"finalPlacement,omitempty"`
}

type Team struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	LogoURL      *string   `json:"logoUrl,omitempty"`
	PrimaryColor *string   `json:"primaryColor,omitempty"`
}
